// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfjAoMl4sp-ddbRPQuhnA8--Z1MDhag70',
    appId: '1:1012761432888:web:7b3b9055f995c91301e7cd',
    messagingSenderId: '1012761432888',
    projectId: 'masroufi-be20c',
    authDomain: 'masroufi-be20c.firebaseapp.com',
    storageBucket: 'masroufi-be20c.firebasestorage.app',
    measurementId: 'G-SL7SY9XJBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMnUYiZYVaGU4mmBzK3DByVzQifdU7ti0',
    appId: '1:1012761432888:android:967f23b520f471da01e7cd',
    messagingSenderId: '1012761432888',
    projectId: 'masroufi-be20c',
    storageBucket: 'masroufi-be20c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkTSxVXr6EuyOi77zQWG_6drCtigNLqxo',
    appId: '1:1012761432888:ios:b62b53a08337c12201e7cd',
    messagingSenderId: '1012761432888',
    projectId: 'masroufi-be20c',
    storageBucket: 'masroufi-be20c.firebasestorage.app',
    iosBundleId: 'com.example.masroufi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkTSxVXr6EuyOi77zQWG_6drCtigNLqxo',
    appId: '1:1012761432888:ios:b62b53a08337c12201e7cd',
    messagingSenderId: '1012761432888',
    projectId: 'masroufi-be20c',
    storageBucket: 'masroufi-be20c.firebasestorage.app',
    iosBundleId: 'com.example.masroufi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfjAoMl4sp-ddbRPQuhnA8--Z1MDhag70',
    appId: '1:1012761432888:web:943078741b9b9ba401e7cd',
    messagingSenderId: '1012761432888',
    projectId: 'masroufi-be20c',
    authDomain: 'masroufi-be20c.firebaseapp.com',
    storageBucket: 'masroufi-be20c.firebasestorage.app',
    measurementId: 'G-FYQPGCMPJP',
  );
}
